In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\Data_Analytics\Tableau\Portfolio\listings.csv")
pd.set_option('display.max.columns', 200)
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,48154,https://www.airbnb.com/rooms/48154,20260626225654,2026-06-27,city scrape,Precioso apartamento con wifi,"Second floor in a late 19th century estate, ve...",NaN,https://a0.muscache.com/pictures/1109085/9c0d4...,219476,https://www.airbnb.com/users/show/219476,1.462513e+18,https://www.airbnb.com/users/profile/146251295...,Antonio,NaN,15.0,9.0,15.0,5.0,Spain,Un saludo a todos. Espero que os pongáis en co...,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/users/219476/profil...,NaN,4.0,NaN,NaN,t,t,NaN,MORVEDRE,LA SAIDIA,39.483750,-0.375020,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Hair dryer"", ""Kitchen"", ""Microwave"", ""TV"", ""...",$145.50,2026-08-19,2026-08-21,291.00,145.50,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",2.0,25.0,2.0,4.0,10.0,25.0,2.9,23.0,NaN,t,0,2,15,98,2026-06-27,223,35,4,98,27,210,30555.0,2010-10-12,2026-06-14,4.61,4.67,4.65,4.85,4.80,4.53,4.52,Valencia - Regional registration number<br />V...,NaN,4,4,0,0,1.17
1,137143,https://www.airbnb.com/rooms/137143,20260626225654,2026-07-03,previous scrape,PENTHOUSE ON FRONT LINE BEACH,NaN,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,670775,https://www.airbnb.com/users/show/670775,1.462526e+18,https://www.airbnb.com/users/profile/146252564...,Attico Valencia,NaN,15.0,0.0,15.0,0.0,"Valencia, Spain",We manage a curated collection of 5 penthouse ...,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/User/...,NaN,5.0,NaN,NaN,t,t,NaN,EL SALER,POBLATS DEL SUD,39.363350,-0.319320,Entire rental unit,Entire home/apt,7,NaN,1.5 baths,1.0,NaN,"[""Free parking on premises"", ""Wifi"", ""Pets all...",NaN,NaN,NaN,NaN,NaN,NaN,10.0,170.0,10.0,10.0,170.0,170.0,10.0,170.0,NaN,t,0,0,0,0,2026-07-03,1,0,0,0,0,0,NaN,2013-07-02,2013-07-02,0.00,5.00,5.00,5.00,5.00,4.00,4.00,Valencia - Regional registration number<br />V...,NaN,5,5,0,0,0.01
2,149715,https://www.airbnb.com/rooms/149715,20260626225654,2026-06-27,city scrape,1900 Style Valencian Beach Home for 10px,Typical town house with 5 bedrooms and 4 bathr...,NaN,https://a0.muscache.com/pictures/808b4883-c57f...,5947,https://www.airbnb.com/users/show/5947,1.462507e+18,https://www.airbnb.com/users/profile/146250651...,Susana Barbara,NaN,17.0,5.0,15.0,5.0,"Valencia, Spain",I’ve been traveling since I was 15. I moved ...,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/User-...,NaN,1.0,NaN,NaN,t,t,NaN,CABANYAL-CANYAMELAR,POBLATS MARITIMS,39.467460,-0.328130,Entire home,Entire home/apt,10,4.0,4 baths,5.0,7.0,"[""High chair"", ""Free dryer \u2013 In unit"", ""T...",$485.00,2026-08-05,2026-08-07,970.00,485.00,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,9.0,1.0,3.0,9.0,9.0,2.1,9.0,NaN,t,2,6,18,258,2026-06-27,344,43,4,91,42,255,123675.0,2011-07-23,2026-06-21,4.67,4.71,4.58,4.84,4.88,4.62,4.61,Spain - National registration number<br />ESFC...,NaN,1,1,0,0,1.89
3,165971,https://www.airbnb.com/rooms/165971,20260626225654,2026-06-27,city scrape,★ Architectural touch! ★,"Hola! I am ready to welcome you in my apt., wh...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,791187,https://www.airbnb.com/users/show/791187,1.462530e+18,https://www.airbnb.com/users/profile/146252953...,Inés,NaN,14.0,11.0,14.0,11.0,"Valencia, Spain","Architect, world traveler, and food enthusiast...",NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/User/...,NaN,15.0,NaN,NaN,t,t,NaN,LA ROQUETA,EXTRAMURS,39.467900,-0.382060,Entire rental unit,Entire home/apt,5,1.0,1 bath,1.0,3.0,"[""Room-darkening shades"", ""Portable fans"", ""Ha...",$211.20,2026-08-16,2026-08-21,1056.00,211.20,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,10.0,1.0,5.0,10.0,10.0,4.9,10.0,NaN,t,0,10,21,97,2026-06-27,612,47,1,92,44,255,53856.0,2011-07-23,2026-05-28,4.88,4.91,4.89,4.89,4.88,4.84,4.85,Valencia - Regional registration number<br />V...,NaN,12,12,0,0,3.37
4,182221,https://www.airbnb.com/rooms/182221,20260626225654,2026-06-27,city scrape,Apartments Calatrava City Valencia,NaN,NaN,https://a0.muscache.com/pictures/1161513/9f7ac...,1315567,https://www.airbnb.com/users/show/1315567,1.462517e+18,https://www.airbnb.com/users/profile/146251727...,Patente Lino,NaN,14.0,8.0,14.0,8.0,"Valencia, Spain","Io amo Viaggiare, Amo la Spagna, l'Italia ed i...",NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/users/1315567/profi...,NaN,2.0,NaN,NaN,t,f,NaN,AIORA,CAMINS AL GRAU,39.463212,-0.343279,Entire condo,Entire home/apt,5,NaN,1 bath,2.0,5.0,"[""High chair"", ""Toaster"", ""Smoking allowed"", ""...",$352.20,2026-07-05,2026-07-10,1761.00,352.20,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",3.0,11.0,3.0,5.0,10.0,11.0,3.7,10.8,NaN,t,16,29,59,149,2026-06-27,10,1,0,149,1,6,2113.0,2015-08-04,2026-01-04,4.60,4.50,4.50,4.70,4.70,4.40,4.50,Valencia - Regional registration number<br />V...,NaN,2,2,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7846,1715265355544470004,https://www.airbnb.com/rooms/1715265355544470004,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style,"Quiet yet wonderfully central, this neighborho...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1.467209e+18,https://www.airbnb.com/users/profile/146720931...,SariStays,NaN,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/User/...,NaN,16.0,NaN,NaN,t,t,NaN,MORVEDRE,LA SAIDIA,39.482030,-0.375040,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$85.12,2026-08-29,2026-09-08,851.20,85.12,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,NaN,t,4,13,30,200,2026-06-27,0,0,0,118,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,NaN,8,8,0,0,NaN
7847,1715277710199680475,https://www.airbnb.com/rooms/1715277710199680475,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style L,"Quiet yet wonderfully central, this neighborho...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1.467209e+18,https://www.airbnb.com/users/profile/146720931...,SariStays,NaN,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/User/...,NaN,16.0,NaN,NaN,t,t,NaN,MORVEDRE,LA SAIDIA,39.482412,-0.376806,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$99.00,2026-09-12,2026-09-22,990.00,99.00,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,NaN,t,5,13,26,206,2026-06-27,0,0,0,124,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,NaN,8,8,0,0,NaN
7848,1715338905046170969,https://www.airbnb.com/rooms/1715338905046170969,20260626225654,2026-06-27,city scrape,Casa,Relax in this unique and quiet accommodation. ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,178769887,https://www.airbnb.com/users/show/178769887,1.463071e+18,https://www.airbnb.com/users/profile/146307087...,Anaïs,NaN,8.0,3.0,8.0,3.0,NaN,NaN,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/2d3c4...,NaN,1.0,NaN,NaN,t,t,NaN,CASTELLAR-L'OLIVERAL,POBLATS DEL SUD,39.423490,-0.347064,Entire home,Entire home/apt,6,1.0,1 bath,3.0,2.0,"[""Air conditioning"", ""Washer"", ""Beach access"",...",$227.50,2026-06-28,2026-06-30,455.00,227.50,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,365.0,1.0,3.0,365.0,365.0,1.5,365.0,NaN,t,26,56,86,92,2026-06-27,0,0,0,92,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />V...,NaN,1,1,0,0,NaN
7849,1716011270454334701,https://www.airbnb.com/rooms/1716011270454334701,20260626225654,2026-06-27,city scrape,Habitación Privada,Take a break from your day-to-day life and rel...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,518335658,https://www.airbnb.com/users/show/518335658,1.470332e+18,https://www.airbnb.com/users/profile/147033211...,Alejandro,NaN,3.0,0.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/User-...,NaN,2.0,NaN,NaN,t,t,NaN,BETERO,POBLATS MARITIMS,39.475980,-0.335430,Private room in rental unit,Private room,1,2.0,2 shared baths,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Clothing...",$45.65,2026-07-04,2026-07-15,502.12,45.65,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,40.0,10.0,11.0,40.0,40.0,10.2,40.0,NaN,t,23,53,58,58,2026-06-27,0,0,0,58,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,NaN,2,0,2,0,NaN
7850,1716042440767325687,https://www.airbnb.com/rooms/1716042440767325687,20260626225654,2026-06-27,city scrape,Piso de diseño al lado de la playa,Welcome to your seaside retreat in Valencia! T...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,24288283,https://www.airbnb.com/users/show/24288283,1.465286e+18,https://www.airbnb.com/users/profile/146528589...,Pablo,NaN,11.0,6.0,11.0,6.0,"Valencia, Spain",NaN,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/b5716...,NaN,1.0,NaN,NaN,t,t,NaN,LA MALVA-ROSA,POBLATS MARITIMS,39.479886,-0.328940,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Air conditioning"", ""Washer"", ""Free dryer \u2...",NaN,2026-09-18,2026-09-21,NaN,NaN,"{""quote"": {""taxes"": null, ""currency"": null, ""d...",3.0,1125.0,3.0,3.0,30.0,1125.0,3.0,279.0,NaN,NaN,0,0,7,97,2026-06-27,0,0,0,97,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />A...,NaN,1,1,0,0,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7851 entries, 0 to 7850
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7851 non-null   int64
 1   listing_url                                   7851 non-null   str
 2   scrape_id                                     7851 non-null   int64
 3   last_scraped                                  7851 non-null   str
 4   source                                        7851 non-null   str
 5   name                                          7851 non-null   str
 6   description                                   7678 non-null   str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   7851 non-null   str
 9   host_id                                       7851 non-null   int64
 10  host_url                                      7851 non-null   str
 11  host_profile_id                               7848 non-null   float64
 12  host_profile_url                              7848 non-null   str
 13  host_name                                     7848 non-null   str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      7848 non-null   float64
 16  hosts_time_as_user_months                     7848 non-null   float64
 17  hosts_time_as_host_years                      7848 non-null   float64
 18  hosts_time_as_host_months                     7848 non-null   float64
 19  host_location                                 5783 non-null   str
 20  host_about                                    4361 non-null   str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             7848 non-null   str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              7848 non-null   str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           7848 non-null   float64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          7848 non-null   str
 32  host_identity_verified                        7848 non-null   str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        7851 non-null   str
 35  neighbourhood_group_cleansed                  7851 non-null   str
 36  latitude                                      7851 non-null   float64
 37  longitude                                     7851 non-null   float64
 38  property_type                                 7851 non-null   str
 39  room_type                                     7851 non-null   str
 40  accommodates                                  7851 non-null   int64
 41  bathrooms                                     6517 non-null   float64
 42  bathrooms_text                                7844 non-null   str
 43  bedrooms                                      6372 non-null   float64
 44  beds                                          6866 non-null   float64
 45  amenities                                     7851 non-null   str
 46  price                                         7267 non-null   str
 47  price_quote_checkin_date                      7420 non-null   str
 48  price_quote_checkout_date                     7420 non-null   str
 49  price_quote_total_price                       7267 non-null   float64
 50  price_quote_price_per_night                   7267 non-null   float64
 51  price_quote_raw                               7420 non-null   str
 52  minimum_nights                                7848 non-null   float64
 53  maximum_nights                                7848 non-null   float64
 54  minimum_minimum_nights                        7848 non-null   float64
 55  maximum_minimum_nights                        7848 non-null   float64
 56  minimum_maximum_nights                        7848 non-null   float64
 57  maximum_maximum_nights                        7848 non-null   float64
 58  minimum_nights_avg_ntm                        7851 non-null   float64
 59  maximum_nights_avg_ntm                        7851 non-null   float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              7820 non-null   str
 62  availability_30                               7851 non-null   int64
 63  availability_60                               7851 non-null   int64
 64  availability_90                               7851 non-null   int64
 65  availability_365                              7851 non-null   int64
 66  calendar_last_scraped                         7851 non-null   str
 67  number_of_reviews                             7851 non-null   int64
 68  number_of_reviews_ltm                         7851 non-null   int64
 69  number_of_reviews_l30d                        7851 non-null   int64
 70  availability_eoy                              7851 non-null   int64
 71  number_of_reviews_ly                          7851 non-null   int64
 72  estimated_occupancy_l365d                     7851 non-null   int64
 73  estimated_revenue_l365d                       7267 non-null   float64
 74  first_review                                  6921 non-null   str
 75  last_review                                   6921 non-null   str
 76  review_scores_rating                          6921 non-null   float64
 77  review_scores_accuracy                        6920 non-null   float64
 78  review_scores_cleanliness                     6921 non-null   float64
 79  review_scores_checkin                         6920 non-null   float64
 80  review_scores_communication                   6920 non-null   float64
 81  review_scores_location                        6920 non-null   float64
 82  review_scores_value                           6920 non-null   float64
 83  license                                       6349 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                7851 non-null   int64
 86  calculated_host_listings_count_entire_homes   7851 non-null   int64
 87  calculated_host_listings_count_private_rooms  7851 non-null   int64
 88  calculated_host_listings_count_shared_rooms   7851 non-null   int64
 89  reviews_per_month                             6921 non-null   float64
dtypes: float64(42), int64(18), str(30)
memory usage: 23.7 MB

In [4]:
df = df.drop_duplicates()

In [6]:
df = df.drop(columns = ['instant_bookable', 'calendar_updated', 'neighbourhood', 'host_verifications', 'host_total_listings_count', 'host_neighbourhood', 'host_thumbnail_url', 'host_acceptance_rate', 'host_response_rate', 'host_response_time', 'host_since', 'neighborhood_overview'])

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7851 entries, 0 to 7850
Data columns (total 78 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7851 non-null   int64
 1   listing_url                                   7851 non-null   str
 2   scrape_id                                     7851 non-null   int64
 3   last_scraped                                  7851 non-null   str
 4   source                                        7851 non-null   str
 5   name                                          7851 non-null   str
 6   description                                   7678 non-null   str
 7   picture_url                                   7851 non-null   str
 8   host_id                                       7851 non-null   int64
 9   host_url                                      7851 non-null   str
 10  host_profile_id                               7848 non-null   float64
 11  host_profile_url                              7848 non-null   str
 12  host_name                                     7848 non-null   str
 13  hosts_time_as_user_years                      7848 non-null   float64
 14  hosts_time_as_user_months                     7848 non-null   float64
 15  hosts_time_as_host_years                      7848 non-null   float64
 16  hosts_time_as_host_months                     7848 non-null   float64
 17  host_location                                 5783 non-null   str
 18  host_about                                    4361 non-null   str
 19  host_is_superhost                             7848 non-null   str
 20  host_picture_url                              7848 non-null   str
 21  host_listings_count                           7848 non-null   float64
 22  host_has_profile_pic                          7848 non-null   str
 23  host_identity_verified                        7848 non-null   str
 24  neighbourhood_cleansed                        7851 non-null   str
 25  neighbourhood_group_cleansed                  7851 non-null   str
 26  latitude                                      7851 non-null   float64
 27  longitude                                     7851 non-null   float64
 28  property_type                                 7851 non-null   str
 29  room_type                                     7851 non-null   str
 30  accommodates                                  7851 non-null   int64
 31  bathrooms                                     6517 non-null   float64
 32  bathrooms_text                                7844 non-null   str
 33  bedrooms                                      6372 non-null   float64
 34  beds                                          6866 non-null   float64
 35  amenities                                     7851 non-null   str
 36  price                                         7267 non-null   str
 37  price_quote_checkin_date                      7420 non-null   str
 38  price_quote_checkout_date                     7420 non-null   str
 39  price_quote_total_price                       7267 non-null   float64
 40  price_quote_price_per_night                   7267 non-null   float64
 41  price_quote_raw                               7420 non-null   str
 42  minimum_nights                                7848 non-null   float64
 43  maximum_nights                                7848 non-null   float64
 44  minimum_minimum_nights                        7848 non-null   float64
 45  maximum_minimum_nights                        7848 non-null   float64
 46  minimum_maximum_nights                        7848 non-null   float64
 47  maximum_maximum_nights                        7848 non-null   float64
 48  minimum_nights_avg_ntm                        7851 non-null   float64
 49  maximum_nights_avg_ntm                        7851 non-null   float64
 50  has_availability                              7820 non-null   str
 51  availability_30                               7851 non-null   int64
 52  availability_60                               7851 non-null   int64
 53  availability_90                               7851 non-null   int64
 54  availability_365                              7851 non-null   int64
 55  calendar_last_scraped                         7851 non-null   str
 56  number_of_reviews                             7851 non-null   int64
 57  number_of_reviews_ltm                         7851 non-null   int64
 58  number_of_reviews_l30d                        7851 non-null   int64
 59  availability_eoy                              7851 non-null   int64
 60  number_of_reviews_ly                          7851 non-null   int64
 61  estimated_occupancy_l365d                     7851 non-null   int64
 62  estimated_revenue_l365d                       7267 non-null   float64
 63  first_review                                  6921 non-null   str
 64  last_review                                   6921 non-null   str
 65  review_scores_rating                          6921 non-null   float64
 66  review_scores_accuracy                        6920 non-null   float64
 67  review_scores_cleanliness                     6921 non-null   float64
 68  review_scores_checkin                         6920 non-null   float64
 69  review_scores_communication                   6920 non-null   float64
 70  review_scores_location                        6920 non-null   float64
 71  review_scores_value                           6920 non-null   float64
 72  license                                       6349 non-null   str
 73  calculated_host_listings_count                7851 non-null   int64
 74  calculated_host_listings_count_entire_homes   7851 non-null   int64
 75  calculated_host_listings_count_private_rooms  7851 non-null   int64
 76  calculated_host_listings_count_shared_rooms   7851 non-null   int64
 77  reviews_per_month                             6921 non-null   float64
dtypes: float64(30), int64(18), str(30)
memory usage: 23.0 MB

In [8]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_is_superhost,host_picture_url,host_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,48154,https://www.airbnb.com/rooms/48154,20260626225654,2026-06-27,city scrape,Precioso apartamento con wifi,"Second floor in a late 19th century estate, ve...",https://a0.muscache.com/pictures/1109085/9c0d4...,219476,https://www.airbnb.com/users/show/219476,1.462513e+18,https://www.airbnb.com/users/profile/146251295...,Antonio,15.0,9.0,15.0,5.0,Spain,Un saludo a todos. Espero que os pongáis en co...,t,https://a0.muscache.com/im/users/219476/profil...,4.0,t,t,MORVEDRE,LA SAIDIA,39.483750,-0.375020,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Hair dryer"", ""Kitchen"", ""Microwave"", ""TV"", ""...",$145.50,2026-08-19,2026-08-21,291.00,145.50,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",2.0,25.0,2.0,4.0,10.0,25.0,2.9,23.0,t,0,2,15,98,2026-06-27,223,35,4,98,27,210,30555.0,2010-10-12,2026-06-14,4.61,4.67,4.65,4.85,4.80,4.53,4.52,Valencia - Regional registration number<br />V...,4,4,0,0,1.17
1,137143,https://www.airbnb.com/rooms/137143,20260626225654,2026-07-03,previous scrape,PENTHOUSE ON FRONT LINE BEACH,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,670775,https://www.airbnb.com/users/show/670775,1.462526e+18,https://www.airbnb.com/users/profile/146252564...,Attico Valencia,15.0,0.0,15.0,0.0,"Valencia, Spain",We manage a curated collection of 5 penthouse ...,f,https://a0.muscache.com/im/pictures/user/User/...,5.0,t,t,EL SALER,POBLATS DEL SUD,39.363350,-0.319320,Entire rental unit,Entire home/apt,7,NaN,1.5 baths,1.0,NaN,"[""Free parking on premises"", ""Wifi"", ""Pets all...",NaN,NaN,NaN,NaN,NaN,NaN,10.0,170.0,10.0,10.0,170.0,170.0,10.0,170.0,t,0,0,0,0,2026-07-03,1,0,0,0,0,0,NaN,2013-07-02,2013-07-02,0.00,5.00,5.00,5.00,5.00,4.00,4.00,Valencia - Regional registration number<br />V...,5,5,0,0,0.01
2,149715,https://www.airbnb.com/rooms/149715,20260626225654,2026-06-27,city scrape,1900 Style Valencian Beach Home for 10px,Typical town house with 5 bedrooms and 4 bathr...,https://a0.muscache.com/pictures/808b4883-c57f...,5947,https://www.airbnb.com/users/show/5947,1.462507e+18,https://www.airbnb.com/users/profile/146250651...,Susana Barbara,17.0,5.0,15.0,5.0,"Valencia, Spain",I’ve been traveling since I was 15. I moved ...,t,https://a0.muscache.com/im/pictures/user/User-...,1.0,t,t,CABANYAL-CANYAMELAR,POBLATS MARITIMS,39.467460,-0.328130,Entire home,Entire home/apt,10,4.0,4 baths,5.0,7.0,"[""High chair"", ""Free dryer \u2013 In unit"", ""T...",$485.00,2026-08-05,2026-08-07,970.00,485.00,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,9.0,1.0,3.0,9.0,9.0,2.1,9.0,t,2,6,18,258,2026-06-27,344,43,4,91,42,255,123675.0,2011-07-23,2026-06-21,4.67,4.71,4.58,4.84,4.88,4.62,4.61,Spain - National registration number<br />ESFC...,1,1,0,0,1.89
3,165971,https://www.airbnb.com/rooms/165971,20260626225654,2026-06-27,city scrape,★ Architectural touch! ★,"Hola! I am ready to welcome you in my apt., wh...",https://a0.muscache.com/pictures/hosting/Hosti...,791187,https://www.airbnb.com/users/show/791187,1.462530e+18,https://www.airbnb.com/users/profile/146252953...,Inés,14.0,11.0,14.0,11.0,"Valencia, Spain","Architect, world traveler, and food enthusiast...",t,https://a0.muscache.com/im/pictures/user/User/...,15.0,t,t,LA ROQUETA,EXTRAMURS,39.467900,-0.382060,Entire rental unit,Entire home/apt,5,1.0,1 bath,1.0,3.0,"[""Room-darkening shades"", ""Portable fans"", ""Ha...",$211.20,2026-08-16,2026-08-21,1056.00,211.20,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,10.0,1.0,5.0,10.0,10.0,4.9,10.0,t,0,10,21,97,2026-06-27,612,47,1,92,44,255,53856.0,2011-07-23,2026-05-28,4.88,4.91,4.89,4.89,4.88,4.84,4.85,Valencia - Regional registration number<br />V...,12,12,0,0,3.37
4,182221,https://www.airbnb.com/rooms/182221,20260626225654,2026-06-27,city scrape,Apartments Calatrava City Valencia,NaN,https://a0.muscache.com/pictures/1161513/9f7ac...,1315567,https://www.airbnb.com/users/show/1315567,1.462517e+18,https://www.airbnb.com/users/profile/146251727...,Patente Lino,14.0,8.0,14.0,8.0,"Valencia, Spain","Io amo Viaggiare, Amo la Spagna, l'Italia ed i...",f,https://a0.muscache.com/im/users/1315567/profi...,2.0,t,f,AIORA,CAMINS AL GRAU,39.463212,-0.343279,Entire condo,Entire home/apt,5,NaN,1 bath,2.0,5.0,"[""High chair"", ""Toaster"", ""Smoking allowed"", ""...",$352.20,2026-07-05,2026-07-10,1761.00,352.20,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",3.0,11.0,3.0,5.0,10.0,11.0,3.7,10.8,t,16,29,59,149,2026-06-27,10,1,0,149,1,6,2113.0,2015-08-04,2026-01-04,4.60,4.50,4.50,4.70,4.70,4.40,4.50,Valencia - Regional registration number<br />V...,2,2,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7846,1715265355544470004,https://www.airbnb.com/rooms/1715265355544470004,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1.467209e+18,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482030,-0.375040,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$85.12,2026-08-29,2026-09-08,851.20,85.12,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,4,13,30,200,2026-06-27,0,0,0,118,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,8,8,0,0,NaN
7847,1715277710199680475,https://www.airbnb.com/rooms/1715277710199680475,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style L,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1.467209e+18,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482412,-0.376806,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$99.00,2026-09-12,2026-09-22,990.00,99.00,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,5,13,26,206,2026-06-27,0,0,0,124,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,8,8,0,0,NaN
7848,1715338905046170969,https://www.airbnb.com/rooms/1715338905046170969,20260626225654,2026-06-27,city scrape,Casa,Relax in this unique and quiet accommodation. ...,https://a0.muscache.com/pictures/hosting/Hosti...,178769887,https://www.airbnb.com/users/show/178769887,1.463071e+18,https://www.airbnb.com/users/profile/146307087...,Anaïs,8.0,3.0,8.0,3.0,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/2d3c4...,1.0,t,t,CASTELLAR-L'OLIVERAL,POBLATS DEL SUD,39.423490,-0.347064,Entire home,Entire home/apt,6,1.0,1 bath,3.0,2.0,"[""Air conditioning"", ""Washer"", ""Beach access"",...",$227.50,2026-06-28,2026-06-30,455.00,227.50,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,365.0,1.0,3.0,365.0,365.0,1.5,365.0,t,26,56,86,92,2026-06-27,0,0,0,92,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />V...,1,1,0,0,NaN
7849,1716011270454334701,https://www.airbnb.com/rooms/1716011270454334701,20260626225654,2026-06-27,city scrape,Habitación Privada,Take a break from your day-to-day life and rel...,https://a0.muscache.com/pictures/hosting/Hosti...,518335658,https://www.airbnb.com/users/show/518335658,1.470332e+18,https://www.airbnb.com/users/profile/147033211...,Alejandro,3.0,0.0,3.0,0.0,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/User-...,2.0,t,t,BETERO,POBLATS MARITIMS,39.475980,-0.335430,Private room in rental unit,Private room,1,2.0,2 shared baths,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Clothing...",$45.65,2026-07-04,2026-07-15,502.12,45.65,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,40.0,10.0,11.0,40.0,40.0,10.2,40.0,t,23,53,58,58,2026-06-27,0,0,0,58,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,2,0,2,0,NaN
7850,1716042440767325687,https://www.airbnb.com/rooms/1716042440767325687,20260626225654,2026-06-27,city scrape,Piso de diseño al lado de la playa,Welcome to your seaside retreat in Valencia! T...,https://a0.muscache.com/pictures/hosting/Hosti...,24288283,https://www.airbnb.com/users/show/24288283,1.465286e+18,https://www.airbnb.com/users/profile/146528589...,Pablo,11.0,6.0,11.0,6.0,"Valencia, Spain",NaN,f,https://a0.muscache.com/im/pictures/user/b5716...,1.0,t,t,LA MALVA-ROSA,POBLATS MARITIMS,39.479886,-0.328940,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Air conditioning"", ""Washer"", ""Free dryer \u2...",NaN,2026-09-18,2026-09-21,NaN,NaN,"{""quote"": {""taxes"": null, ""currency"": null, ""d...",3.0,1125.0,3.0,3.0,30.0,1125.0,3.0,279.0,NaN,0,0,7,97,2026-06-27,0,0,0,97,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />A...,1,1,0,0,NaN

In [9]:
df.isnull().sum()

id                                                0
listing_url                                       0
scrape_id                                         0
last_scraped                                      0
source                                            0
                                               ...
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
calculated_host_listings_count_private_rooms      0
calculated_host_listings_count_shared_rooms       0
reviews_per_month                               930
Length: 78, dtype: int64

In [10]:
df.nunique()

id                                              7851
listing_url                                     7851
scrape_id                                          1
last_scraped                                       3
source                                             2
                                                ...
calculated_host_listings_count                    47
calculated_host_listings_count_entire_homes       44
calculated_host_listings_count_private_rooms      19
calculated_host_listings_count_shared_rooms        5
reviews_per_month                                664
Length: 78, dtype: int64

In [14]:
df["name"] = df["name"].str.strip("123._/★")
df["host_name"] = df["host_name"].str.strip("123._/")
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_is_superhost,host_picture_url,host_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,48154,https://www.airbnb.com/rooms/48154,20260626225654,2026-06-27,city scrape,Precioso apartamento con wifi,"Second floor in a late 19th century estate, ve...",https://a0.muscache.com/pictures/1109085/9c0d4...,219476,https://www.airbnb.com/users/show/219476,1.462513e+18,https://www.airbnb.com/users/profile/146251295...,Antonio,15.0,9.0,15.0,5.0,Spain,Un saludo a todos. Espero que os pongáis en co...,t,https://a0.muscache.com/im/users/219476/profil...,4.0,t,t,MORVEDRE,LA SAIDIA,39.483750,-0.375020,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Hair dryer"", ""Kitchen"", ""Microwave"", ""TV"", ""...",$145.50,2026-08-19,2026-08-21,291.00,145.50,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",2.0,25.0,2.0,4.0,10.0,25.0,2.9,23.0,t,0,2,15,98,2026-06-27,223,35,4,98,27,210,30555.0,2010-10-12,2026-06-14,4.61,4.67,4.65,4.85,4.80,4.53,4.52,Valencia - Regional registration number<br />V...,4,4,0,0,1.17
1,137143,https://www.airbnb.com/rooms/137143,20260626225654,2026-07-03,previous scrape,PENTHOUSE ON FRONT LINE BEACH,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,670775,https://www.airbnb.com/users/show/670775,1.462526e+18,https://www.airbnb.com/users/profile/146252564...,Attico Valencia,15.0,0.0,15.0,0.0,"Valencia, Spain",We manage a curated collection of 5 penthouse ...,f,https://a0.muscache.com/im/pictures/user/User/...,5.0,t,t,EL SALER,POBLATS DEL SUD,39.363350,-0.319320,Entire rental unit,Entire home/apt,7,NaN,1.5 baths,1.0,NaN,"[""Free parking on premises"", ""Wifi"", ""Pets all...",NaN,NaN,NaN,NaN,NaN,NaN,10.0,170.0,10.0,10.0,170.0,170.0,10.0,170.0,t,0,0,0,0,2026-07-03,1,0,0,0,0,0,NaN,2013-07-02,2013-07-02,0.00,5.00,5.00,5.00,5.00,4.00,4.00,Valencia - Regional registration number<br />V...,5,5,0,0,0.01
2,149715,https://www.airbnb.com/rooms/149715,20260626225654,2026-06-27,city scrape,900 Style Valencian Beach Home for 10px,Typical town house with 5 bedrooms and 4 bathr...,https://a0.muscache.com/pictures/808b4883-c57f...,5947,https://www.airbnb.com/users/show/5947,1.462507e+18,https://www.airbnb.com/users/profile/146250651...,Susana Barbara,17.0,5.0,15.0,5.0,"Valencia, Spain",I’ve been traveling since I was 15. I moved ...,t,https://a0.muscache.com/im/pictures/user/User-...,1.0,t,t,CABANYAL-CANYAMELAR,POBLATS MARITIMS,39.467460,-0.328130,Entire home,Entire home/apt,10,4.0,4 baths,5.0,7.0,"[""High chair"", ""Free dryer \u2013 In unit"", ""T...",$485.00,2026-08-05,2026-08-07,970.00,485.00,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,9.0,1.0,3.0,9.0,9.0,2.1,9.0,t,2,6,18,258,2026-06-27,344,43,4,91,42,255,123675.0,2011-07-23,2026-06-21,4.67,4.71,4.58,4.84,4.88,4.62,4.61,Spain - National registration number<br />ESFC...,1,1,0,0,1.89
3,165971,https://www.airbnb.com/rooms/165971,20260626225654,2026-06-27,city scrape,Architectural touch!,"Hola! I am ready to welcome you in my apt., wh...",https://a0.muscache.com/pictures/hosting/Hosti...,791187,https://www.airbnb.com/users/show/791187,1.462530e+18,https://www.airbnb.com/users/profile/146252953...,Inés,14.0,11.0,14.0,11.0,"Valencia, Spain","Architect, world traveler, and food enthusiast...",t,https://a0.muscache.com/im/pictures/user/User/...,15.0,t,t,LA ROQUETA,EXTRAMURS,39.467900,-0.382060,Entire rental unit,Entire home/apt,5,1.0,1 bath,1.0,3.0,"[""Room-darkening shades"", ""Portable fans"", ""Ha...",$211.20,2026-08-16,2026-08-21,1056.00,211.20,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,10.0,1.0,5.0,10.0,10.0,4.9,10.0,t,0,10,21,97,2026-06-27,612,47,1,92,44,255,53856.0,2011-07-23,2026-05-28,4.88,4.91,4.89,4.89,4.88,4.84,4.85,Valencia - Regional registration number<br />V...,12,12,0,0,3.37
4,182221,https://www.airbnb.com/rooms/182221,20260626225654,2026-06-27,city scrape,Apartments Calatrava City Valencia,NaN,https://a0.muscache.com/pictures/1161513/9f7ac...,1315567,https://www.airbnb.com/users/show/1315567,1.462517e+18,https://www.airbnb.com/users/profile/146251727...,Patente Lino,14.0,8.0,14.0,8.0,"Valencia, Spain","Io amo Viaggiare, Amo la Spagna, l'Italia ed i...",f,https://a0.muscache.com/im/users/1315567/profi...,2.0,t,f,AIORA,CAMINS AL GRAU,39.463212,-0.343279,Entire condo,Entire home/apt,5,NaN,1 bath,2.0,5.0,"[""High chair"", ""Toaster"", ""Smoking allowed"", ""...",$352.20,2026-07-05,2026-07-10,1761.00,352.20,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",3.0,11.0,3.0,5.0,10.0,11.0,3.7,10.8,t,16,29,59,149,2026-06-27,10,1,0,149,1,6,2113.0,2015-08-04,2026-01-04,4.60,4.50,4.50,4.70,4.70,4.40,4.50,Valencia - Regional registration number<br />V...,2,2,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7846,1715265355544470004,https://www.airbnb.com/rooms/1715265355544470004,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1.467209e+18,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482030,-0.375040,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$85.12,2026-08-29,2026-09-08,851.20,85.12,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,4,13,30,200,2026-06-27,0,0,0,118,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,8,8,0,0,NaN
7847,1715277710199680475,https://www.airbnb.com/rooms/1715277710199680475,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style L,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1.467209e+18,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482412,-0.376806,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$99.00,2026-09-12,2026-09-22,990.00,99.00,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,5,13,26,206,2026-06-27,0,0,0,124,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,8,8,0,0,NaN
7848,1715338905046170969,https://www.airbnb.com/rooms/1715338905046170969,20260626225654,2026-06-27,city scrape,Casa,Relax in this unique and quiet accommodation. ...,https://a0.muscache.com/pictures/hosting/Hosti...,178769887,https://www.airbnb.com/users/show/178769887,1.463071e+18,https://www.airbnb.com/users/profile/146307087...,Anaïs,8.0,3.0,8.0,3.0,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/2d3c4...,1.0,t,t,CASTELLAR-L'OLIVERAL,POBLATS DEL SUD,39.423490,-0.347064,Entire home,Entire home/apt,6,1.0,1 bath,3.0,2.0,"[""Air conditioning"", ""Washer"", ""Beach access"",...",$227.50,2026-06-28,2026-06-30,455.00,227.50,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,365.0,1.0,3.0,365.0,365.0,1.5,365.0,t,26,56,86,92,2026-06-27,0,0,0,92,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />V...,1,1,0,0,NaN
7849,1716011270454334701,https://www.airbnb.com/rooms/1716011270454334701,20260626225654,2026-06-27,city scrape,Habitación Privada,Take a break from your day-to-day life and rel...,https://a0.muscache.com/pictures/hosting/Hosti...,518335658,https://www.airbnb.com/users/show/518335658,1.470332e+18,https://www.airbnb.com/users/profile/147033211...,Alejandro,3.0,0.0,3.0,0.0,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/User-...,2.0,t,t,BETERO,POBLATS MARITIMS,39.475980,-0.335430,Private room in rental unit,Private room,1,2.0,2 shared baths,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Clothing...",$45.65,2026-07-04,2026-07-15,502.12,45.65,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,40.0,10.0,11.0,40.0,40.0,10.2,40.0,t,23,53,58,58,2026-06-27,0,0,0,58,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />E...,2,0,2,0,NaN
7850,1716042440767325687,https://www.airbnb.com/rooms/1716042440767325687,20260626225654,2026-06-27,city scrape,Piso de diseño al lado de la playa,Welcome to your seaside retreat in Valencia! T...,https://a0.muscache.com/pictures/hosting/Hosti...,24288283,https://www.airbnb.com/users/show/24288283,1.465286e+18,https://www.airbnb.com/users/profile/146528589...,Pablo,11.0,6.0,11.0,6.0,"Valencia, Spain",NaN,f,https://a0.muscache.com/im/pictures/user/b5716...,1.0,t,t,LA MALVA-ROSA,POBLATS MARITIMS,39.479886,-0.328940,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Air conditioning"", ""Washer"", ""Free dryer \u2...",NaN,2026-09-18,2026-09-21,NaN,NaN,"{""quote"": {""taxes"": null, ""currency"": null, ""d...",3.0,1125.0,3.0,3.0,30.0,1125.0,3.0,279.0,NaN,0,0,7,97,2026-06-27,0,0,0,97,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valencia - Regional registration number<br />A...,1,1,0,0,NaN

In [15]:
df=df.fillna('')
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_is_superhost,host_picture_url,host_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,48154,https://www.airbnb.com/rooms/48154,20260626225654,2026-06-27,city scrape,Precioso apartamento con wifi,"Second floor in a late 19th century estate, ve...",https://a0.muscache.com/pictures/1109085/9c0d4...,219476,https://www.airbnb.com/users/show/219476,1462512950298658048.0,https://www.airbnb.com/users/profile/146251295...,Antonio,15.0,9.0,15.0,5.0,Spain,Un saludo a todos. Espero que os pongáis en co...,t,https://a0.muscache.com/im/users/219476/profil...,4.0,t,t,MORVEDRE,LA SAIDIA,39.483750,-0.375020,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Hair dryer"", ""Kitchen"", ""Microwave"", ""TV"", ""...",$145.50,2026-08-19,2026-08-21,291.0,145.5,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",2.0,25.0,2.0,4.0,10.0,25.0,2.9,23.0,t,0,2,15,98,2026-06-27,223,35,4,98,27,210,30555.0,2010-10-12,2026-06-14,4.61,4.67,4.65,4.85,4.8,4.53,4.52,Valencia - Regional registration number<br />V...,4,4,0,0,1.17
1,137143,https://www.airbnb.com/rooms/137143,20260626225654,2026-07-03,previous scrape,PENTHOUSE ON FRONT LINE BEACH,,https://a0.muscache.com/pictures/hosting/Hosti...,670775,https://www.airbnb.com/users/show/670775,1462525647630459904.0,https://www.airbnb.com/users/profile/146252564...,Attico Valencia,15.0,0.0,15.0,0.0,"Valencia, Spain",We manage a curated collection of 5 penthouse ...,f,https://a0.muscache.com/im/pictures/user/User/...,5.0,t,t,EL SALER,POBLATS DEL SUD,39.363350,-0.319320,Entire rental unit,Entire home/apt,7,,1.5 baths,1.0,,"[""Free parking on premises"", ""Wifi"", ""Pets all...",,,,,,,10.0,170.0,10.0,10.0,170.0,170.0,10.0,170.0,t,0,0,0,0,2026-07-03,1,0,0,0,0,0,,2013-07-02,2013-07-02,0.0,5.0,5.0,5.0,5.0,4.0,4.0,Valencia - Regional registration number<br />V...,5,5,0,0,0.01
2,149715,https://www.airbnb.com/rooms/149715,20260626225654,2026-06-27,city scrape,900 Style Valencian Beach Home for 10px,Typical town house with 5 bedrooms and 4 bathr...,https://a0.muscache.com/pictures/808b4883-c57f...,5947,https://www.airbnb.com/users/show/5947,1462506514113160192.0,https://www.airbnb.com/users/profile/146250651...,Susana Barbara,17.0,5.0,15.0,5.0,"Valencia, Spain",I’ve been traveling since I was 15. I moved ...,t,https://a0.muscache.com/im/pictures/user/User-...,1.0,t,t,CABANYAL-CANYAMELAR,POBLATS MARITIMS,39.467460,-0.328130,Entire home,Entire home/apt,10,4.0,4 baths,5.0,7.0,"[""High chair"", ""Free dryer \u2013 In unit"", ""T...",$485.00,2026-08-05,2026-08-07,970.0,485.0,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,9.0,1.0,3.0,9.0,9.0,2.1,9.0,t,2,6,18,258,2026-06-27,344,43,4,91,42,255,123675.0,2011-07-23,2026-06-21,4.67,4.71,4.58,4.84,4.88,4.62,4.61,Spain - National registration number<br />ESFC...,1,1,0,0,1.89
3,165971,https://www.airbnb.com/rooms/165971,20260626225654,2026-06-27,city scrape,Architectural touch!,"Hola! I am ready to welcome you in my apt., wh...",https://a0.muscache.com/pictures/hosting/Hosti...,791187,https://www.airbnb.com/users/show/791187,1462529534006996224.0,https://www.airbnb.com/users/profile/146252953...,Inés,14.0,11.0,14.0,11.0,"Valencia, Spain","Architect, world traveler, and food enthusiast...",t,https://a0.muscache.com/im/pictures/user/User/...,15.0,t,t,LA ROQUETA,EXTRAMURS,39.467900,-0.382060,Entire rental unit,Entire home/apt,5,1.0,1 bath,1.0,3.0,"[""Room-darkening shades"", ""Portable fans"", ""Ha...",$211.20,2026-08-16,2026-08-21,1056.0,211.2,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,10.0,1.0,5.0,10.0,10.0,4.9,10.0,t,0,10,21,97,2026-06-27,612,47,1,92,44,255,53856.0,2011-07-23,2026-05-28,4.88,4.91,4.89,4.89,4.88,4.84,4.85,Valencia - Regional registration number<br />V...,12,12,0,0,3.37
4,182221,https://www.airbnb.com/rooms/182221,20260626225654,2026-06-27,city scrape,Apartments Calatrava City Valencia,,https://a0.muscache.com/pictures/1161513/9f7ac...,1315567,https://www.airbnb.com/users/show/1315567,1462517272797878784.0,https://www.airbnb.com/users/profile/146251727...,Patente Lino,14.0,8.0,14.0,8.0,"Valencia, Spain","Io amo Viaggiare, Amo la Spagna, l'Italia ed i...",f,https://a0.muscache.com/im/users/1315567/profi...,2.0,t,f,AIORA,CAMINS AL GRAU,39.463212,-0.343279,Entire condo,Entire home/apt,5,,1 bath,2.0,5.0,"[""High chair"", ""Toaster"", ""Smoking allowed"", ""...",$352.20,2026-07-05,2026-07-10,1761.0,352.2,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",3.0,11.0,3.0,5.0,10.0,11.0,3.7,10.8,t,16,29,59,149,2026-06-27,10,1,0,149,1,6,2113.0,2015-08-04,2026-01-04,4.6,4.5,4.5,4.7,4.7,4.4,4.5,Valencia - Regional registration number<br />V...,2,2,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7846,1715265355544470004,https://www.airbnb.com/rooms/1715265355544470004,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1467209319777753600.0,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482030,-0.375040,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$85.12,2026-08-29,2026-09-08,851.2,85.12,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,4,13,30,200,2026-06-27,0,0,0,118,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />E...,8,8,0,0,
7847,1715277710199680475,https://www.airbnb.com/rooms/1715277710199680475,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style L,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1467209319777753600.0,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482412,-0.376806,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$99.00,2026-09-12,2026-09-22,990.0,99.0,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,5,13,26,206,2026-06-27,0,0,0,124,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />E...,8,8,0,0,
7848,1715338905046170969,https://www.airbnb.com/rooms/1715338905046170969,20260626225654,2026-06-27,city scrape,Casa,Relax in this unique and quiet accommodation. ...,https://a0.muscache.com/pictures/hosting/Hosti...,178769887,https://www.airbnb.com/users/show/178769887,1463070878838611200.0,https://www.airbnb.com/users/profile/146307087...,Anaïs,8.0,3.0,8.0,3.0,,,f,https://a0.muscache.com/im/pictures/user/2d3c4...,1.0,t,t,CASTELLAR-L'OLIVERAL,POBLATS DEL SUD,39.423490,-0.347064,Entire home,Entire home/apt,6,1.0,1 bath,3.0,2.0,"[""Air conditioning"", ""Washer"", ""Beach access"",...",$227.50,2026-06-28,2026-06-30,455.0,227.5,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,365.0,1.0,3.0,365.0,365.0,1.5,365.0,t,26,56,86,92,2026-06-27,0,0,0,92,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />V...,1,1,0,0,
7849,1716011270454334701,https://www.airbnb.com/rooms/1716011270454334701,20260626225654,2026-06-27,city scrape,Habitación Privada,Take a break from your day-to-day life and rel...,https://a0.muscache.com/pictures/hosting/Hosti...,518335658,https://www.airbnb.com/users/show/518335658,1470332111359759104.0,https://www.airbnb.com/users/profile/147033211...,Alejandro,3.0,0.0,3.0,0.0,,,f,https://a0.muscache.com/im/pictures/user/User-...,2.0,t,t,BETERO,POBLATS MARITIMS,39.475980,-0.335430,Private room in rental unit,Private room,1,2.0,2 shared baths,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Clothing...",$45.65,2026-07-04,2026-07-15,502.12,45.65,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,40.0,10.0,11.0,40.0,40.0,10.2,40.0,t,23,53,58,58,2026-06-27,0,0,0,58,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />E...,2,0,2,0,
7850,1716042440767325687,https://www.airbnb.com/rooms/1716042440767325687,20260626225654,2026-06-27,city scrape,Piso de diseño al lado de la playa,Welcome to your seaside retreat in Valencia! T...,https://a0.muscache.com/pictures/hosting/Hosti...,24288283,https://www.airbnb.com/users/show/24288283,1465285893794688256.0,https://www.airbnb.com/users/profile/146528589...,Pablo,11.0,6.0,11.0,6.0,"Valencia, Spain",,f,https://a0.muscache.com/im/pictures/user/b5716...,1.0,t,t,LA MALVA-ROSA,POBLATS MARITIMS,39.479886,-0.328940,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Air conditioning"", ""Washer"", ""Free dryer \u2...",,2026-09-18,2026-09-21,,,"{""quote"": {""taxes"": null, ""currency"": null, ""d...",3.0,1125.0,3.0,3.0,30.0,1125.0,3.0,279.0,,0,0,7,97,2026-06-27,0,0,0,97,0,0,,,,,,,,,,,Valencia - Regional registration number<br />A...,1,1,0,0,

In [16]:
#for x in df.index:
#    if df.loc[x, "host_location"] != 'Valencia, Spain':
#        df.loc(x, 'host_location') = 'Valencia, Spain'
df.loc[df["host_location"] != "Valencia, Spain", "host_location"] = ("Valencia, Spain")
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_is_superhost,host_picture_url,host_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,48154,https://www.airbnb.com/rooms/48154,20260626225654,2026-06-27,city scrape,Precioso apartamento con wifi,"Second floor in a late 19th century estate, ve...",https://a0.muscache.com/pictures/1109085/9c0d4...,219476,https://www.airbnb.com/users/show/219476,1462512950298658048.0,https://www.airbnb.com/users/profile/146251295...,Antonio,15.0,9.0,15.0,5.0,"Valencia, Spain",Un saludo a todos. Espero que os pongáis en co...,t,https://a0.muscache.com/im/users/219476/profil...,4.0,t,t,MORVEDRE,LA SAIDIA,39.483750,-0.375020,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Hair dryer"", ""Kitchen"", ""Microwave"", ""TV"", ""...",$145.50,2026-08-19,2026-08-21,291.0,145.5,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",2.0,25.0,2.0,4.0,10.0,25.0,2.9,23.0,t,0,2,15,98,2026-06-27,223,35,4,98,27,210,30555.0,2010-10-12,2026-06-14,4.61,4.67,4.65,4.85,4.8,4.53,4.52,Valencia - Regional registration number<br />V...,4,4,0,0,1.17
1,137143,https://www.airbnb.com/rooms/137143,20260626225654,2026-07-03,previous scrape,PENTHOUSE ON FRONT LINE BEACH,,https://a0.muscache.com/pictures/hosting/Hosti...,670775,https://www.airbnb.com/users/show/670775,1462525647630459904.0,https://www.airbnb.com/users/profile/146252564...,Attico Valencia,15.0,0.0,15.0,0.0,"Valencia, Spain",We manage a curated collection of 5 penthouse ...,f,https://a0.muscache.com/im/pictures/user/User/...,5.0,t,t,EL SALER,POBLATS DEL SUD,39.363350,-0.319320,Entire rental unit,Entire home/apt,7,,1.5 baths,1.0,,"[""Free parking on premises"", ""Wifi"", ""Pets all...",,,,,,,10.0,170.0,10.0,10.0,170.0,170.0,10.0,170.0,t,0,0,0,0,2026-07-03,1,0,0,0,0,0,,2013-07-02,2013-07-02,0.0,5.0,5.0,5.0,5.0,4.0,4.0,Valencia - Regional registration number<br />V...,5,5,0,0,0.01
2,149715,https://www.airbnb.com/rooms/149715,20260626225654,2026-06-27,city scrape,900 Style Valencian Beach Home for 10px,Typical town house with 5 bedrooms and 4 bathr...,https://a0.muscache.com/pictures/808b4883-c57f...,5947,https://www.airbnb.com/users/show/5947,1462506514113160192.0,https://www.airbnb.com/users/profile/146250651...,Susana Barbara,17.0,5.0,15.0,5.0,"Valencia, Spain",I’ve been traveling since I was 15. I moved ...,t,https://a0.muscache.com/im/pictures/user/User-...,1.0,t,t,CABANYAL-CANYAMELAR,POBLATS MARITIMS,39.467460,-0.328130,Entire home,Entire home/apt,10,4.0,4 baths,5.0,7.0,"[""High chair"", ""Free dryer \u2013 In unit"", ""T...",$485.00,2026-08-05,2026-08-07,970.0,485.0,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,9.0,1.0,3.0,9.0,9.0,2.1,9.0,t,2,6,18,258,2026-06-27,344,43,4,91,42,255,123675.0,2011-07-23,2026-06-21,4.67,4.71,4.58,4.84,4.88,4.62,4.61,Spain - National registration number<br />ESFC...,1,1,0,0,1.89
3,165971,https://www.airbnb.com/rooms/165971,20260626225654,2026-06-27,city scrape,Architectural touch!,"Hola! I am ready to welcome you in my apt., wh...",https://a0.muscache.com/pictures/hosting/Hosti...,791187,https://www.airbnb.com/users/show/791187,1462529534006996224.0,https://www.airbnb.com/users/profile/146252953...,Inés,14.0,11.0,14.0,11.0,"Valencia, Spain","Architect, world traveler, and food enthusiast...",t,https://a0.muscache.com/im/pictures/user/User/...,15.0,t,t,LA ROQUETA,EXTRAMURS,39.467900,-0.382060,Entire rental unit,Entire home/apt,5,1.0,1 bath,1.0,3.0,"[""Room-darkening shades"", ""Portable fans"", ""Ha...",$211.20,2026-08-16,2026-08-21,1056.0,211.2,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,10.0,1.0,5.0,10.0,10.0,4.9,10.0,t,0,10,21,97,2026-06-27,612,47,1,92,44,255,53856.0,2011-07-23,2026-05-28,4.88,4.91,4.89,4.89,4.88,4.84,4.85,Valencia - Regional registration number<br />V...,12,12,0,0,3.37
4,182221,https://www.airbnb.com/rooms/182221,20260626225654,2026-06-27,city scrape,Apartments Calatrava City Valencia,,https://a0.muscache.com/pictures/1161513/9f7ac...,1315567,https://www.airbnb.com/users/show/1315567,1462517272797878784.0,https://www.airbnb.com/users/profile/146251727...,Patente Lino,14.0,8.0,14.0,8.0,"Valencia, Spain","Io amo Viaggiare, Amo la Spagna, l'Italia ed i...",f,https://a0.muscache.com/im/users/1315567/profi...,2.0,t,f,AIORA,CAMINS AL GRAU,39.463212,-0.343279,Entire condo,Entire home/apt,5,,1 bath,2.0,5.0,"[""High chair"", ""Toaster"", ""Smoking allowed"", ""...",$352.20,2026-07-05,2026-07-10,1761.0,352.2,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",3.0,11.0,3.0,5.0,10.0,11.0,3.7,10.8,t,16,29,59,149,2026-06-27,10,1,0,149,1,6,2113.0,2015-08-04,2026-01-04,4.6,4.5,4.5,4.7,4.7,4.4,4.5,Valencia - Regional registration number<br />V...,2,2,0,0,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7846,1715265355544470004,https://www.airbnb.com/rooms/1715265355544470004,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1467209319777753600.0,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482030,-0.375040,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$85.12,2026-08-29,2026-09-08,851.2,85.12,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,4,13,30,200,2026-06-27,0,0,0,118,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />E...,8,8,0,0,
7847,1715277710199680475,https://www.airbnb.com/rooms/1715277710199680475,20260626225654,2026-06-27,city scrape,Saristays Valencia Luxe Style L,"Quiet yet wonderfully central, this neighborho...",https://a0.muscache.com/pictures/hosting/Hosti...,100725734,https://www.airbnb.com/users/show/100725734,1467209319777753600.0,https://www.airbnb.com/users/profile/146720931...,SariStays,9.0,8.0,9.0,8.0,"Valencia, Spain","Hi, I’m Tom from SariStays. We believe great s...",t,https://a0.muscache.com/im/pictures/user/User/...,16.0,t,t,MORVEDRE,LA SAIDIA,39.482412,-0.376806,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""High chair"", ""Toaster"", ""Paid parking off pr...",$99.00,2026-09-12,2026-09-22,990.0,99.0,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,180.0,10.0,10.0,180.0,180.0,10.0,180.0,t,5,13,26,206,2026-06-27,0,0,0,124,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />E...,8,8,0,0,
7848,1715338905046170969,https://www.airbnb.com/rooms/1715338905046170969,20260626225654,2026-06-27,city scrape,Casa,Relax in this unique and quiet accommodation. ...,https://a0.muscache.com/pictures/hosting/Hosti...,178769887,https://www.airbnb.com/users/show/178769887,1463070878838611200.0,https://www.airbnb.com/users/profile/146307087...,Anaïs,8.0,3.0,8.0,3.0,"Valencia, Spain",,f,https://a0.muscache.com/im/pictures/user/2d3c4...,1.0,t,t,CASTELLAR-L'OLIVERAL,POBLATS DEL SUD,39.423490,-0.347064,Entire home,Entire home/apt,6,1.0,1 bath,3.0,2.0,"[""Air conditioning"", ""Washer"", ""Beach access"",...",$227.50,2026-06-28,2026-06-30,455.0,227.5,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",1.0,365.0,1.0,3.0,365.0,365.0,1.5,365.0,t,26,56,86,92,2026-06-27,0,0,0,92,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />V...,1,1,0,0,
7849,1716011270454334701,https://www.airbnb.com/rooms/1716011270454334701,20260626225654,2026-06-27,city scrape,Habitación Privada,Take a break from your day-to-day life and rel...,https://a0.muscache.com/pictures/hosting/Hosti...,518335658,https://www.airbnb.com/users/show/518335658,1470332111359759104.0,https://www.airbnb.com/users/profile/147033211...,Alejandro,3.0,0.0,3.0,0.0,"Valencia, Spain",,f,https://a0.muscache.com/im/pictures/user/User-...,2.0,t,t,BETERO,POBLATS MARITIMS,39.475980,-0.335430,Private room in rental unit,Private room,1,2.0,2 shared baths,1.0,1.0,"[""Toaster"", ""Room-darkening shades"", ""Clothing...",$45.65,2026-07-04,2026-07-15,502.12,45.65,"{""quote"": {""taxes"": null, ""currency"": ""EUR"", ""...",10.0,40.0,10.0,11.0,40.0,40.0,10.2,40.0,t,23,53,58,58,2026-06-27,0,0,0,58,0,0,0.0,,,,,,,,,,Valencia - Regional registration number<br />E...,2,0,2,0,
7850,1716042440767325687,https://www.airbnb.com/rooms/1716042440767325687,20260626225654,2026-06-27,city scrape,Piso de diseño al lado de la playa,Welcome to your seaside retreat in Valencia! T...,https://a0.muscache.com/pictures/hosting/Hosti...,24288283,https://www.airbnb.com/users/show/24288283,1465285893794688256.0,https://www.airbnb.com/users/profile/146528589...,Pablo,11.0,6.0,11.0,6.0,"Valencia, Spain",,f,https://a0.muscache.com/im/pictures/user/b5716...,1.0,t,t,LA MALVA-ROSA,POBLATS MARITIMS,39.479886,-0.328940,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Air conditioning"", ""Washer"", ""Free dryer \u2...",,2026-09-18,2026-09-21,,,"{""quote"": {""taxes"": null, ""currency"": null, ""d...",3.0,1125.0,3.0,3.0,30.0,1125.0,3.0,279.0,,0,0,7,97,2026-06-27,0,0,0,97,0,0,,,,,,,,,,,Valencia - Regional registration number<br />A...,1,1,0,0,

In [17]:
#df2 = pd.read_csv(r"D:\Data_Analytics\Tableau\Portfolio\calendar.csv")
#df.merge(df2, how = 'inner', on = ['id', 'listing_id'])

In [18]:
#df.to_excel(r"D:\Data_Analytics\Python\Portfolio\listings.xlsx", index = False)

In [30]:
price = pd.to_numeric(df["price_quote_price_per_night"], errors="coerce")
price

0       145.50
1          NaN
2       485.00
3       211.20
4       352.20
         ...
7846     85.12
7847     99.00
7848    227.50
7849     45.65
7850       NaN
Name: price_quote_price_per_night, Length: 7851, dtype: float64

In [ ]:
price.dropna.plot(kind="hist")

In [27]:

type(df['price_quote_price_per_night'])
#df.plot.bar(x = 'neighbourhood_cleansed', y = 'price_quote_price_per_night')

pandas.Series