# Scraping Data from a Real Website + Pandas

In [4]:
from bs4 import BeautifulSoup
import requests

In [5]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"

headers = {
    'User-Agent': 'LearningScraperApp/1.0 (cracer2004@gmail.com)'
}

page = requests.get(url, headers=headers)

if page.status_code == 200:
    soup = BeautifulSoup(page.text, 'html.parser')
    print(soup.title.text) 
else:
    print(f"Помилка доступу: {page.status_code}")

List of largest companies by revenue - Wikipedia

In [6]:
soup = BeautifulSoup(page.text, 'html')
print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of largest companies by revenue - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"8b2db0fc-0dc6-4a5b-aff2-e560faa43d04","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_by_revenue","wgTitle":"List of largest companies by revenue","wgCurRevisionId":1368559287,"wgRevisionId":1368559287,"wgArticleId":997455,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of companies by revenue","Lists of largest companies"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_by_revenue","wgRelevantArticleId":997455,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":20000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Business":{"class":"List","importance":"Mid"},"Companies":{"class":"List","importance":"High"},"Lists":{"class":"List","importance":"Mid"},"Project-independent assessment":{"class":"List","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q900297","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.16" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Amazon_2024.svg/1280px-Amazon_2024.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail" property="og:image"/>
  <meta content="1200" property="og:image:width"/>
  <meta content="402" property="og:image:height"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of largest companies by revenue - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=List_of_largest_companies_by_revenue&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>
  <link href="auth.wikimedia.org" rel="dns-prefetch"/>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_by_revenue rootpage-List_of_largest_companies_by_revenue skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2">
           <a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2">

In [7]:
soup.find('table', class_ = "wikitable sortable sticky-header-multi sort-under")

<table class="wikitable sortable sticky-header-multi sort-under" id="mwKQ" style="text-align:left;">
<tbody id="mwKg"><tr id="mwKw">
<th id="mwLA" rowspan="2" scope="col">Ranks</th>
<th id="mwLQ" rowspan="2" scope="col">Name</th>
<th id="mwLg" rowspan="2" scope="col">Industry</th>
<th id="mwLw" scope="col">Revenue</th>
<th id="mwMA" scope="col">Profit</th>
<th id="mwMQ" rowspan="2" scope="col">Employees</th>
<th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>
<th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>
<th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th></tr>
<tr id="mwPA">
<th colspan="2" id="mwPQ" scope="col"><small id="mwPg">USD (in billions)</small><!-- billions is correct, comma is thousands separator, not decimal mark. 100,000 million = 100 billion  --></th></tr>
<tr id="mwPw">
<th id="mwQA" scope="row">1</th>
<td id="mwQQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwQg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td><td id="mwQw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwRA" rel="mw:WikiLink" title="Retail">Retail</a><br id="mwRQ"/> <a href="https://en.wikipedia.org/wiki/Information_technology" id="mwRg" rel="mw:WikiLink" title="Information technology">Information technology</a></td><td id="mwRw" style="text-align:center;">716 <span about="#mwt22" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwSA" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwSQ" style="text-align:center;">79.9</td><td id="mwSg" style="text-align:right;">1,576,000</td><td id="mwSw" rowspan="2"><span about="#mwt23" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"USA"}},"i":0}}]}' id="mwTA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-type="drawing" data-file-width="1235" decoding="async" height="12" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_United_States.svg" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/40px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/60px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> United States</td><td about="#mwt24" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwTQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwTg"><sup about="#mwt27" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-6"}}' id="cite_ref-6" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-6" id="mwTw"><span class="mw-reflink-text" id="mwUA"><span class="cite-bracket" id="mwUQ">[</span>5<span class="cite-bracket" id="mwUg">]</span></span></a></sup></td></tr>
<tr id="mwUw">
<th id="mwVA" scope="col">2</th>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwVg" rel="mw:WikiLink" title="Walmart">Walmart</a></td><td id="mwVw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwWA" rel="mw:WikiLink" title="Retail">Retail</a></td><td id="mwWQ" style="text-align:center;">713 <span about="#mwt28" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwWw" style="text-align:center;">21.8</td><td id="mwXA" style="text-align:right;">2,100,000</td><td about="#mwt29" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwXQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwXg"><sup about="#mwt32" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"W"},"body":{"id":"mw-reference-text-cite_note-W-7"}}' id="cite_ref-W_7-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-W-7" id="mwXw"><span class="mw-reflink-text" id="mwYA"><span class="cite-bracket" id="mwYQ">[</span>6<span class="cite-bracket" id="mwYg">]</span></span></a></sup></td></tr>
<tr id="mwYw">
<th id="mwZA" scope="row">3</th>
<td id="mwZQ"><a href="https://en.wikipedia.org/wiki/State_Grid_Corporation_of_China" id="mwZg" rel="mw:WikiLink" title="State Grid Corporation of China">State Grid Corporation of China</a></td><td id="mwZw"><a href="https://en.wikipedia.org/wiki/Electric_utility" id="mwaA" rel="mw:WikiLink" title="Electric utility">Electricity</a></td><td id="mwaQ" style="text-align:center;">545 <span about="#mwt33" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwag" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwaw" style="text-align:center;">9.2</td><td id="mwbA" style="text-align:right;">1,361,423</td>
<td id="mwbQ"><span about="#mwt34" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwbg" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td>
<td about="#mwt35" class="table-yes2" data-mw='{"parts":["| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}]}' data-sort-value="Yes" id="mwbw" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td>
<td id="mwcA"><sup about="#mwt38" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-8"}}' id="cite_ref-8" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-8" id="mwcQ"><span class="mw-reflink-text" id="mwcg"><span class="cite-bracket" id="mwcw">[</span>7<span class="cite-bracket" id="mwdA">]</span></span></a></sup></td></tr>
<tr id="mwdQ">
<th id="mwdg" scope="row">4</th>
<td id="mwdw"><a href="https://en.wikipedia.org/wiki/Saudi_Aramco" id="mweA" rel="mw:WikiLink" title="Saudi Aramco">Saudi Aramco</a></td><td id="mweQ" rowspan="3"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Oil_and_gas" id="mweg" rel="mw:WikiLink" title="Oil and gas">Oil and gas</a></td><td id="mwew" style="text-align:center;">480 <span about="#mwt39" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwfA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwfQ" style="text-align:center;">106</td><td id="mwfg" style="text-align:right;">73,311</td><td id="mwfw"><span about="#mwt40" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"Saudi Arabia"}},"i":0}}]}' id="mwgA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/Saudi_Arabia" title="Saudi Arabia"><img alt="Saudi Arabia" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Saudi_Arabia.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/40px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/60px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> Saudi Arabia</td><td about="#mwt41" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwgQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwgg"><sup about="#mwt44" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-9"}}' id="cite_ref-9" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-9" id="mwgw"><span class="mw-reflink-text" id="mwhA"><span class="cite-bracket" id="mwhQ">[</span>8<span class="cite-bracket" id="mwhg">]</span></span></a></sup></td></tr>
<tr id="mwhw">
<th id="mwiA" scope="row">5</th>
<td id="mwiQ"><a href="https://en.wikipedia.org/wiki/China_National_Petroleum_Corporation" id="mwig" rel="mw:WikiLink" title="China National Petroleum Corporation">China National Petroleum Corporation</a></td><td id="mwiw" style="text-align:center;">476 <span about="#mwt45" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwjA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwjQ" style="text-align:center;">25.2</td><td id="mwjg" style="text-align:right;">1,026,301</td><td id="mwjw" rowspan="2"><span about="#mwt46" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwkA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td><td about="#mwt47" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwkQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwkg"><sup about="#mwt50" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-10"}}' id="cite_ref-10" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-10" id="mwkw"><span class="mw-reflink-text" id="mwlA"><span class="cite-bracket" id="mwlQ">[</span>9<span class="cite-bracket" id="mwlg">]</span></span></a></sup></td></tr>
<tr id="mwlw">
<th id="mwmA" scope="row">6</th>
<td id="mwmQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/China_Petrochemical_Corporation" id="mwmg" rel="mw:WikiLink" title="China Petrochemical Corporation">China Petrochemical Corporation</a></td>

In [10]:
table = soup.find('table', class_ = "wikitable sortable sticky-header-multi sort-under")

In [11]:
world_titles = table.find_all('th')

In [12]:
world_titles

[<th id="mwLA" rowspan="2" scope="col">Ranks</th>,
 <th id="mwLQ" rowspan="2" scope="col">Name</th>,
 <th id="mwLg" rowspan="2" scope="col">Industry</th>,
 <th id="mwLw" scope="col">Revenue</th>,
 <th id="mwMA" scope="col">Profit</th>,
 <th id="mwMQ" rowspan="2" scope="col">Employees</th>,
 <th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>,
 <th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>,
 <th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th>,
 <th colspan="2" id="mwPQ" scope="col"><small id="mwPg">USD (in billions)</small><!-- billions is correct, comma is thousands separator, not decimal mark. 100,000 million = 100 billion  --></th>,
 <th id="mwQA" scope="row">1</th>,
 <th id="mwVA" scope="col">2</th>,
 <th id="mwZA" scope="row">3</th>,
 <th id="mwdg" scope="row">4</th>,
 <th id="mwiA" scope="row">5</th>,
 <th id="mwmA" scope="row">6</th>,
 <th id="mwpg">7</th>,
 <th id="mwuA" scope="row">8</th>,
 <th id="mwyA" scope="row">9</th>,
 <th id="mw2A" scope="row">10</th>,
 <th id="mw6A" scope="row">11</th>,
 <th id="mw-A" scope="row">12</th>,
 <th id="mwAQo" scope="row">13</th>,
 <th id="mwARw" scope="row">14</th>,
 <th id="mwATI" scope="row">15</th>,
 <th id="mwAUQ" scope="row">16</th>,
 <th id="mwAVY" scope="row">17</th>,
 <th id="mwAWg" scope="row">18</th>,
 <th id="mwAXo" scope="row">19</th>,
 <th id="mwAYo" scope="row">20</th>,
 <th id="mwAZo" scope="row">21</th>,
 <th id="mwAaw" scope="row">22</th>,
 <th id="mwAb4" scope="row">23</th>,
 <th id="mwAc4" scope="row">24</th>,
 <th id="mwAd4" scope="row">25</th>,
 <th id="mwAfA" scope="row">26</th>,
 <th id="mwAgI" scope="row">27</th>,
 <th id="mwAhQ">28</th>,
 <th id="mwAiY" scope="row">29</th>,
 <th id="mwAjg" scope="row">30</th>,
 <th id="mwAko">31</th>,
 <th id="mwAlw" scope="row">32</th>,
 <th id="mwAm4" scope="row">33</th>,
 <th id="mwAoA" scope="row">34</th>,
 <th id="mwApI" scope="row">35</th>,
 <th id="mwAqI">36</th>,
 <th id="mwArQ" scope="row">37</th>,
 <th id="mwAsY" scope="row">38</th>,
 <th id="mwAtg" scope="row">39</th>,
 <th id="mwAuo" scope="row">40</th>,
 <th id="mwAvo" scope="row">41</th>,
 <th id="mwAww" scope="row">42</th>,
 <th id="mwAxw" scope="row">43</th>,
 <th id="mwAyw" scope="row">44</th>,
 <th id="mwAzw" scope="row">45</th>,
 <th id="mwA04">46</th>,
 <th id="mwA2A">47</th>,
 <th id="mwA3I" scope="row">48</th>,
 <th id="mwA4Q" scope="row">49</th>,
 <th id="mwA5Q" scope="row">50</th>]

In [15]:
world_table_title = [title.text.strip() for title in world_titles]
print(world_table_title)

['Ranks', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees', 'Headquarters[note 1]', 'State-owned', 'Ref.', 'USD (in billions)', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50']

In [83]:
world_table_titles = (world_table_title[1:7])
world_table_titles[5] = 'Headquarters'
world_table_ranks = (world_table_title[10:])
print(world_table_titles)

['Name', 'Industry', 'Revenue', 'Profit', 'Employees', 'Headquarters']

In [22]:
import pandas as pd

In [84]:
data_frame = pd.DataFrame(columns = world_table_titles)

data_frame

Empty DataFrame
Columns: [Name, Industry, Revenue, Profit, Employees, Headquarters]
Index: []

In [62]:
rank_rows = pd.DataFrame(columns = world_table_ranks)
rank_rows

Empty DataFrame
Columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Index: []

[0 rows x 50 columns]

In [34]:
column_data = table.find_all('tr')
column_data

[<tr id="mwKw">
 <th id="mwLA" rowspan="2" scope="col">Ranks</th>
 <th id="mwLQ" rowspan="2" scope="col">Name</th>
 <th id="mwLg" rowspan="2" scope="col">Industry</th>
 <th id="mwLw" scope="col">Revenue</th>
 <th id="mwMA" scope="col">Profit</th>
 <th id="mwMQ" rowspan="2" scope="col">Employees</th>
 <th id="mwMg" rowspan="2" scope="col">Headquarters<sup about="#mwt19" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"group":"note"},"body":{"id":"mw-reference-text-cite_note-5"}}' id="cite_ref-5" rel="dc:references" typeof="mw:Extension/ref"><a data-mw-group="note" href="#cite_note-5" id="mwMw"><span class="mw-reflink-text" id="mwNA"><span class="cite-bracket" id="mwNQ">[</span>note 1<span class="cite-bracket" id="mwNg">]</span></span></a></sup></th>
 <th id="mwNw" rowspan="2" scope="col"><a href="https://en.wikipedia.org/wiki/State-owned_enterprise" id="mwOA" rel="mw:WikiLink" title="State-owned enterprise">State-owned</a></th>
 <th class="unsortable" id="mwOQ" rowspan="2" scope="col"><abbr about="#mwt20" data-mw='{"attribs":[[{"txt":"title"},{"html":"&lt;span typeof=\"mw:Nowiki\" id=\"mwOg\"&gt;Reference(s)&lt;/span&gt;"}]],"parts":[{"template":{"target":{"wt":"Reference heading","href":"./Template:Reference_heading"},"params":{},"i":0}}]}' id="mwOw" title="Reference(s)" typeof="mw:Transclusion mw:ExpandedAttrs">Ref.</abbr></th></tr>,
 <tr id="mwPA">
 <th colspan="2" id="mwPQ" scope="col"><small id="mwPg">USD (in billions)</small><!-- billions is correct, comma is thousands separator, not decimal mark. 100,000 million = 100 billion  --></th></tr>,
 <tr id="mwPw">
 <th id="mwQA" scope="row">1</th>
 <td id="mwQQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwQg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td><td id="mwQw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwRA" rel="mw:WikiLink" title="Retail">Retail</a><br id="mwRQ"/> <a href="https://en.wikipedia.org/wiki/Information_technology" id="mwRg" rel="mw:WikiLink" title="Information technology">Information technology</a></td><td id="mwRw" style="text-align:center;">716 <span about="#mwt22" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwSA" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwSQ" style="text-align:center;">79.9</td><td id="mwSg" style="text-align:right;">1,576,000</td><td id="mwSw" rowspan="2"><span about="#mwt23" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"USA"}},"i":0}}]}' id="mwTA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/United_States" title="United States"><img alt="United States" class="mw-file-element" data-file-height="650" data-file-type="drawing" data-file-width="1235" decoding="async" height="12" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_United_States.svg" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/40px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/60px-Flag_of_the_United_States.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> United States</td><td about="#mwt24" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwTQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwTg"><sup about="#mwt27" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-6"}}' id="cite_ref-6" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-6" id="mwTw"><span class="mw-reflink-text" id="mwUA"><span class="cite-bracket" id="mwUQ">[</span>5<span class="cite-bracket" id="mwUg">]</span></span></a></sup></td></tr>,
 <tr id="mwUw">
 <th id="mwVA" scope="col">2</th>
 <td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwVg" rel="mw:WikiLink" title="Walmart">Walmart</a></td><td id="mwVw"><a href="https://en.wikipedia.org/wiki/Retail" id="mwWA" rel="mw:WikiLink" title="Retail">Retail</a></td><td id="mwWQ" style="text-align:center;">713 <span about="#mwt28" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwWw" style="text-align:center;">21.8</td><td id="mwXA" style="text-align:right;">2,100,000</td><td about="#mwt29" class="table-no2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"nan","href":"./Template:Nan"},"params":{},"i":0}}," "]}' data-sort-value="No" id="mwXQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"No"}' typeof="mw:File"><span title="No"><img alt="No" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="525" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_x.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/20px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_x.svg/40px-Black_x.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwXg"><sup about="#mwt32" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"W"},"body":{"id":"mw-reference-text-cite_note-W-7"}}' id="cite_ref-W_7-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-W-7" id="mwXw"><span class="mw-reflink-text" id="mwYA"><span class="cite-bracket" id="mwYQ">[</span>6<span class="cite-bracket" id="mwYg">]</span></span></a></sup></td></tr>,
 <tr id="mwYw">
 <th id="mwZA" scope="row">3</th>
 <td id="mwZQ"><a href="https://en.wikipedia.org/wiki/State_Grid_Corporation_of_China" id="mwZg" rel="mw:WikiLink" title="State Grid Corporation of China">State Grid Corporation of China</a></td><td id="mwZw"><a href="https://en.wikipedia.org/wiki/Electric_utility" id="mwaA" rel="mw:WikiLink" title="Electric utility">Electricity</a></td><td id="mwaQ" style="text-align:center;">545 <span about="#mwt33" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwag" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwaw" style="text-align:center;">9.2</td><td id="mwbA" style="text-align:right;">1,361,423</td>
 <td id="mwbQ"><span about="#mwt34" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwbg" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td>
 <td about="#mwt35" class="table-yes2" data-mw='{"parts":["| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}]}' data-sort-value="Yes" id="mwbw" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td>
 <td id="mwcA"><sup about="#mwt38" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-8"}}' id="cite_ref-8" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-8" id="mwcQ"><span class="mw-reflink-text" id="mwcg"><span class="cite-bracket" id="mwcw">[</span>7<span class="cite-bracket" id="mwdA">]</span></span></a></sup></td></tr>,
 <tr id="mwdQ">
 <th id="mwdg" scope="row">4</th>
 <td id="mwdw"><a href="https://en.wikipedia.org/wiki/Saudi_Aramco" id="mweA" rel="mw:WikiLink" title="Saudi Aramco">Saudi Aramco</a></td><td id="mweQ" rowspan="3"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Oil_and_gas" id="mweg" rel="mw:WikiLink" title="Oil and gas">Oil and gas</a></td><td id="mwew" style="text-align:center;">480 <span about="#mwt39" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwfA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwfQ" style="text-align:center;">106</td><td id="mwfg" style="text-align:right;">73,311</td><td id="mwfw"><span about="#mwt40" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"Saudi Arabia"}},"i":0}}]}' id="mwgA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/Saudi_Arabia" title="Saudi Arabia"><img alt="Saudi Arabia" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_Saudi_Arabia.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/40px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/60px-Flag_of_Saudi_Arabia.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> Saudi Arabia</td><td about="#mwt41" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwgQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwgg"><sup about="#mwt44" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-9"}}' id="cite_ref-9" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-9" id="mwgw"><span class="mw-reflink-text" id="mwhA"><span class="cite-bracket" id="mwhQ">[</span>8<span class="cite-bracket" id="mwhg">]</span></span></a></sup></td></tr>,
 <tr id="mwhw">
 <th id="mwiA" scope="row">5</th>
 <td id="mwiQ"><a href="https://en.wikipedia.org/wiki/China_National_Petroleum_Corporation" id="mwig" rel="mw:WikiLink" title="China National Petroleum Corporation">China National Petroleum Corporation</a></td><td id="mwiw" style="text-align:center;">476 <span about="#mwt45" data-mw='{"caption":"Decrease","parts":[{"template":{"target":{"wt":"loss","href":"./Template:Loss"},"params":{},"i":0}}]}' id="mwjA" typeof="mw:Transclusion mw:File"><span title="Decrease"><img alt="Decrease" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Decrease2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/20px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Decrease2.svg/40px-Decrease2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span></td><td id="mwjQ" style="text-align:center;">25.2</td><td id="mwjg" style="text-align:right;">1,026,301</td><td id="mwjw" rowspan="2"><span about="#mwt46" class="flagicon" data-mw='{"parts":[{"template":{"target":{"wt":"flagicon","href":"./Template:Flagicon"},"params":{"1":{"wt":"China"}},"i":0}}]}' id="mwkA" typeof="mw:Transclusion"><span class="mw-image-border" typeof="mw:File"><a href="https://en.wikipedia.org/wiki/China" title="China"><img alt="China" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Flag_of_the_People's_Republic_of_China.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/40px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/60px-Flag_of_the_People%27s_Republic_of_China.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/></a></span></span> China</td><td about="#mwt47" class="table-yes2" data-mw='{"parts":["|| ",{"template":{"target":{"wt":"yan","href":"./Template:Yan"},"params":{},"i":0}}," "]}' data-sort-value="Yes" id="mwkQ" style="vertical-align: middle; text-align: center; " typeof="mw:Transclusion"><span class="skin-invert" data-mw='{"caption":"Yes"}' typeof="mw:File"><span title="Yes"><img alt="Yes" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="600" decoding="async" height="13" loading="lazy" resource="https://en.wikipedia.org/wiki/File:Black_check.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/20px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Black_check.svg/40px-Black_check.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="13"/></span></span></td><td id="mwkg"><sup about="#mwt50" class="mw-ref reference" data-mw='{"name":"ref","attrs":{},"body":{"id":"mw-reference-text-cite_note-10"}}' id="cite_ref-10" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-10" id="mwkw"><span class="mw-reflink-text" id="mwlA"><span class="cite-bracket" id="mwlQ">[</span>9<span class="cite-bracket" id="mwlg">]</span></span></a></sup></td></tr>,
 <tr id="mwlw">
 <th id="mwmA" scope="row">6</th>
 <td id="mwmQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/China_Petrochemical_Corporation" id="mwmg" rel="mw:WikiLink" title="China Petrochemical Corporation">China Petrochemical Corporation</a></td>

In [87]:
for row in column_data[2:]:
    row_data = row.find_all('td')    
    individual_row_dat = [data.text.strip() for data in row_data]
    individual_row_data = individual_row_dat[:6]
    #print(individual_row_data)
    length = len(data_frame)
    data_frame.loc[length] = individual_row_data

In [88]:
data_frame

,Name,Industry,Revenue,Profit,Employees,Headquarters
0,Amazon,Retail Information technology,716,79.9,"1,576,000",United States
1,Walmart,Retail,713,21.8,"2,100,000",
2,State Grid Corporation of China,Electricity,545,9.2,"1,361,423",China
3,Saudi Aramco,Oil and gas,480,106,"73,311",Saudi Arabia
4,China National Petroleum Corporation,476,25.2,"1,026,301",China,
5,China Petrochemical Corporation,429,9.3,"513,434",,[10]
6,Apple,Information technology,416,112,"166,000",United States
7,Alphabet,Information technology,402,132,"190,820",
8,UnitedHealth Group,Healthcare,400,14.4,"400,000",
9,Berkshire Hathaway,Financials,371,88.9,"392,400",
10,CVS Health,Healthcare,357,8.3,"259,500",
11,Volkswagen Group,Automotive,348,17.9,"684,025",Germany
12,ExxonMobil,Oil and gas,344,36.0,"61,500",United States
13,Vitol,Commodities,331,13.0,"1,560",Switzerland
14,Shell,Oil and gas,323,19.3,"103,000",United Kingdom
15,China State Construction Engineering,Construction,320,4.2,"382,894",China
16,Toyota,Automotive,312,34.2,"380,793",Japan
17,McKesson,Healthcare,308,3.0,"48,000",United States
18,Microsoft,Information technology,281,101,"228,000",
19,Cencora,Healthcare,262,1.7,"44,000",
20,Trafigura,Commodities,244,7.3,"12,479",Singapore
21,Costco,Retail,242,6.2,"316,000",United States
22,JPMorgan Chase,Financials,239,49.5,"309,926",
23,Industrial and Commercial Bank of China,222,51.4,"419,252",China,
24,Schwarz Gruppe,Retail,220,n/a,"604,000",Germany
25,TotalEnergies,Oil and gas,218,21.3,"102,579",France
26,Glencore,Commodities,217,4.2,"83,426",Switzerland
27,Nvidia,Semiconductors,215,120,"36,000",United States
28,BP,Oil and gas,213,15.2,"79,400",United Kingdom
29,Cardinal Health,Healthcare,205,0.26,"47,520",United States
30,Stellantis,Automotive,204,20.1,"258,275",Netherlands
31,Chevron,Oil and gas,200,21.3,"45,600",United States
32,China Construction Bank,Financials,199,46.9,"376,871",China
33,Samsung Electronics,Electronics,198,11.0,"267,860",South Korea
34,Foxconn,197,4.5,"621,393",Taiwan,
35,Cigna,Healthcare,195,5.1,"71,413",United States
36,Agricultural Bank of China,Financials,192,38.0,"451,003",China
37,China Railway Engineering Corporation,Construction,178,2.1,"314,149",China
38,Cargill,Conglomerate,177,17.6,"160,000",United States
39,Ford Motor Company,Automotive,176,4.3,"177,000",
40,Bank of China,Financials,172,32.7,"306,931",China
41,Bank of America,171,26.5,"212,985",United States,
42,General Motors,Automotive,171,10.1,"163,000",
43,Elevance Health,Healthcare,171,5.9,"104,900",
44,BMW Group,Automotive,168,12.2,"154,950",Germany
45,Mercedes-Benz Group,Automotive,165,15.4,"166,056",Germany
46,Meta Platforms,Social media,164,62.3,"78,450",United States
47,China Railway Construction Corporation,Construction,160,1.7,"336,433",China
48,Baowu,Steel,157,2.4,"258,697",
49,Citigroup,Financials,156,9.2,"237,925",United States

In [90]:
data_frame.to_csv(r'D:\Data_Analytics\Python\Companies.csv', index = False)